# Generated by Django 4.2.9 on 2024-01-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, default='75342', max_length=5, null=True, verbose_name='Код верификации'),
        ),
    ]
