# Generated by Django 4.2.9 on 2024-01-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, default='23786', max_length=5, null=True, verbose_name='Код верификации'),
        ),
    ]
